cat("Launching app\n")
library(SummarizedExperiment)
library(SingleCellExperiment)
library(ephacRTools)
cat("Package loaded\n")
#l_files <- list.files(path = "./" ,pattern = "*.xlsx$", recursive = TRUE, full.names = TRUE)
#se_hAG <- ephacRTools::prepareSE(l_files)
#print(se_hAG)
ephacRTools::tinySEV()
