---
title: "General_imaging_script_clean"
author: "Athena Schumacher"
date: "2025-06-12"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Load Useful Packages and Functions

```{r message=FALSE, warning=FALSE}

source("/Users/athenaschumacher/Downloads/E-Phac:Robinson_Labs/ephacRTools/R/imagingTools.R")
source("/Users/athenaschumacher/Downloads/E-Phac:Robinson_Labs/ephacRTools/R/utilityTools.R")
source("/Users/athenaschumacher/Downloads/E-Phac:Robinson_Labs/ephacRTools/R/prepareSE.R")
source("/Users/athenaschumacher/Downloads/E-Phac:Robinson_Labs/ephacRTools/R/colDatTools.R")

```


```{r}

devtools::load_all()

data("se_iN")

data("se_romk")

colData(se_romk)[15:25,]

```

```{r}

wells <- se_romk$Well
plateIDs <- se_romk$Plate_ID

parent_folder <- "/Volumes/staff/ephacoffice/DColameo/DATA/ROMK"

image_paths_list <- mapply(function(well, plate, location) {
  image_paths(parent_folder, idx = well, plate = plate, location = 7)
}, well = wells, plate = plateIDs, SIMPLIFY = FALSE)

colData(se_hAG)$Image_paths <- image_paths_list 

# Check 
colData(se_hAG)$Image_paths

se_hAG[,se_hAG$Well == "H05"]$Image_paths

```

Visualize the different channels for a given well of a given plate
```{r}

imageval(se_romk, "C09", "22W14457")

```



Adrenal cells

```{r}

wd_path <- "/Users/athenaschumacher/Downloads/E-Phac:Robinson_Labs/excel_files"

pathToTable <- "/Users/athenaschumacher/Downloads/E-Phac:Robinson_Labs/excel_files/NCI_ramp_ATP1A1_080325_18T39421.xlsx"

#plate_ID <- "18T39421"
plate_ID <- "22W14457"

df <- prep_excel(pathToTable)

df <- prep_df(wd_path, df)

df <- filtered_df(df, plate_ID, ion = "Na")

#df <- group_assignment(df, se = "No", pattern = "Cycle", cycle_pattern = c("HP", "WT","Donor2"))
df <- group_assignment(df, se = "No", pattern = "Cycle", cycle_pattern = c("Donor1", "Donor2"))


```

```{r}
se_hAG <- prepareSE(pathToTable)

parent_folder <- "/Volumes/staff/ephacoffice/DColameo/DATA/human_AG_Sinergia"
plate = plate_ID

wells <- se_hAG$Well
plateIDs <- se_hAG$Plate_ID

image_paths_list <- mapply(function(well, plate, location=7) {
  image_paths(parent_folder, idx = well, plate = plate, location = 7)
}, well = wells, plate = plateIDs, SIMPLIFY = FALSE)

colData(se_hAG)$Image_paths <- image_paths_list 

# Check 
colData(se_hAG)$Image_paths

se_hAG[,se_hAG$Well == "H05"]$Image_paths

```


```{r}
se_coldata <- as.data.frame(colData(se_hAG))

df_clean <- df %>%
  select(Well, Plate_ID, Compound, Group) %>%
  distinct(Well, Plate_ID, .keep_all = TRUE)

matched <- left_join(se_coldata, df_clean, by = c("Well", "Plate_ID"))

se_hAG$Compound <- matched$Compound
se_hAG$Group <- matched$Group
se_hAG$Group <- NULL

se_hAG <- group_assignment(se_hAG, se = "Yes", pattern = "Cycle", cycle_pattern = c("Donor1", "Donor2"))

colData(se_hAG)[30:40,]
```

Save Additions as assays
```{r}

se1 <- row_aggregate_SE(se_hAG,
                        metrics = c("Erev"),
                        FUN     = mean,
                        mode    = "by.period")

# 2) mean of last 5 sweeps
se2_mean <- row_aggregate_SE(se_hAG,
                        metrics = "Erev",
                        FUN     = mean,
                        mode    = "last.n",
                        last.n  = 5)

# 2) median of last 5 sweeps 
se2_med <- row_aggregate_SE(se_hAG,
                        metrics = "Erev",
                        FUN     = median,
                        mode    = "last.n",
                        last.n  = 5)

## Check
se_period <- se1

assayNames(se_period)

mat <- assay(se_period, "Erev")
dim(mat)
rownames(mat)
colnames(mat)[1:10]

mat[, 1:6]
head(mat)

summary(as.numeric(mat))

```



Imaging Data
```{r}

directory <- "/Users/athenaschumacher/Downloads/E-Phac:Robinson_Labs/imaging_data"
extension <- "\\.db$"  # Regular expression for files ending with .db

file_list <- list.files(path = directory, pattern = extension, full.names = TRUE)
file_list <- "/Users/athenaschumacher/Downloads/E-Phac:Robinson_Labs/imaging_data/Output_n1_08.03.db"

df_img <- prepareImgDF(file_list, scale_num = TRUE, analysis = "coloc")
df_img <- df_cleaned(df_img)
se_hAG_test <- mergeSEandImg(se_hAG, df_img, tableType = "coloc")
df_img <- prepareImgDF(file_list, scale_num = TRUE, analysis = "pa")
df_img <- df_cleaned(df_img)
se_hAG_test <- mergeSEandImg(se_hAG_test, df_img, tableType = "pa")


set.seed(42)

se_test <- reducedDim.Cellwise(se_test, colNames= c("Mean_Green_scaled", "Mean_Red_scaled"))

plotDimRed(se_test, redDim.method = "UMAP", colorColumns = c("Mean_Green_scaled", "Mean_Red_scaled","Color",  "Group"))

se_red <- se_test[, !is.na(se_test$Color)]

se_red <- reducedDim.Cellwise(se_red, colNames= c("Mean_Green_scaled", "Mean_Red_scaled"))

se_red <- colAG(se_red, assayList = c("Erev"), sweeps = row.names(rowData(se_red)), suffx=".add1")
colData(se_red)

plotDimRed(se_red, redDim.method = "UMAP", colorColumns = c("Mean_Green_scaled", "Mean_Red_scaled","Color",  "Group"))

colData(se1)

se_hAG_test2$Mean.Scaled <- se_hAG_test2$C2$Mean_Scaled

```

```{r}
plot_intensity_distribution(se_hAG_test, plot_type="density")
plot_intensity_distribution(se_hAG_test, plot_type="ecdf")
```

```{r}
TEST_SE <- assign_cell_FINAL(
  SE = se_hAG_test,
  channels = c("C2", "C3"),
  value_col = "Mean",
  classification_method = "clustering",
  color_output = "Color_cluster",
  plot_umap = TRUE,
  k_centers = 4
)

TEST_SE <- assign_cell_FINAL(
  SE = TEST_SE,
  channels = c("C2", "C3"),
  value_col = "Mean",
  classification_method = "manual",
  color_output = "Color_manual",
  threshold_mode = "manual",
  red_thresh = 0.54,
  green_thresh = 0.74
)

colData(TEST_SE)[30:40,]

rowData(TEST_SE)$Additions <- ifelse(rowData(TEST_SE)$Sweep <=24, "Add1", 
                     ifelse(rowData(TEST_SE)$Sweep >24 & rowData(TEST_SE)$Sweep <= 42,  "Add2", 
                     ifelse(rowData(TEST_SE)$Sweep >42 & rowData(TEST_SE)$Sweep <= 60, "Add3", 
                     ifelse(rowData(TEST_SE)$Sweep >60 & rowData(TEST_SE)$Sweep <= 84,"Add4", NA))))

sweeps_to_use <- which(rowData(TEST_SE)$Additions == "Add1")

TEST_SE <- colAG(TEST_SE, assayList = c("Erev"), sweeps = sweeps_to_use)

TEST_SE <- TEST_SE[, complete.cases(TEST_SE$Erev_mean)]

TEST_SE <- TEST_SE[, colData(TEST_SE)$Erev_mean < -0.03 ]

TEST_SE$Erev_mean <- TEST_SE$Erev_mean*1000

plot_well_assignment(TEST_SE)

rowData(TEST_SE)

```

```{r}
imageval(se_GENtest, "L23", "18T39421")

imageval(TEST_SE, "E06", "18T39421")

```

Other visualization plots
```{r}
ggplot(well_summary, aes_string(x = "feature_C3_scaled")) +
  +     geom_histogram(bins = 50) +
  +     ggtitle("Scaled distribution of feature_C3")

ggplot(well_summary, aes_string(x = "feature_C2_scaled")) +
  +     geom_histogram(bins = 50) +
  +     ggtitle("Scaled distribution of feature_C2")

ggplot(well_summary, aes(x = feature_C2_scaled)) +
  geom_histogram(bins = 50) +
  geom_vline(xintercept = green_threshold, color = "darkgreen") +
  ggtitle("Distribution of Scaled Green Channel")

ggplot(well_summary, aes(x = feature_C3_scaled)) +
  geom_histogram(bins = 50) +
  geom_vline(xintercept = red_thresh, color = "red") +
  ggtitle("Distribution of Scaled Red Channel")
```

Shiny APP
```{r}
library(shinydashboard)
library(shinyjqui)
library(waiter)
library(HDF5Array)
library(ggbeeswarm)
library(plotly)
library(shinycssloaders)
```


```{r}
devtools::load_all()

ephacRTools::tinySEV()
```


```{r}

mismatch_idx <- which(colData(SE)$Color != colData(SE_v1)$Color)
head(data.frame(
     Well = colData(SE)$Well[mismatch_idx],
    Plate_ID = colData(SE)$Plate_ID[mismatch_idx],
    Color_plot = colData(SE)$Color[mismatch_idx],
    Color_final = colData(SE_v1)$Color[mismatch_idx] ))

```



ROMK
```{r}

parent_folder <- "/Volumes/staff/ephacoffice/DColameo/DATA/ROMK"

data("se_romk")

wells <- se_romk$Well
plateIDs <- se_romk$Plate_ID

image_paths_list <- mapply(function(well, plate, location) {
  image_paths(parent_folder, idx = well, plate = plate, location = 5)
}, well = wells, plate = plateIDs, SIMPLIFY = FALSE)

colData(se_romk)$Image_paths <- image_paths_list 

# Check 
colData(se_romk)$Image_paths
se_romk[,se_romk$Well == "H05"]$Image_paths


plot_intensity_distribution(se_romk, channels = c("C1", "C2", "C3"), plot_type="density")
plot_intensity_distribution(se_romk, channels = c("C1", "C2", "C3"), plot_type="ecdf")

se_ROMK_assigned2 <- assign_cell_FINAL(
  SE = se_romk,
  channels = c("C1", "C2", "C3"),
  value_col = "Mean",
  classification_method = "clustering",
  color_output = "Color_cluster",
  plot_umap = TRUE,
  k_centers = 4
)

se_ROMK_assigned2 <- assign_cell_FINAL(
  SE = se_ROMK_assigned2,
  channels = c("C1", "C2", "C3"),
  chan2analyze = c("C1", "C2", "C3"),
  value_col = "Mean",
  classification_method = "manual",
  color_output = "Color_manual",
  threshold_mode = "quantile",
  #red_thresh = 0.54,
  #green_thresh = 0.74
  red_quant = 0.665,
  green_quant = 0.665,
  c3_quant = 0.94
)

plot_well_assignment(se_ROMK_assigned)


imageval(se_ROMK_assigned, "G15", "22W14457", green_slice = 3, red_slice = 2)

#colData(se_ROMK_assigned)[30:40,]

#rowData(se_ROMK_assigned)$Additions <- ifelse(rowData(se_ROMK_assigned)$Sweep <=24, "Add1", 
#                     ifelse(rowData(se_ROMK_assigned)$Sweep >24 & rowData(se_ROMK_assigned)$Sweep <= 42,  "Add2", 
#                     ifelse(rowData(se_ROMK_assigned)$Sweep >42 & rowData(se_ROMK_assigned)$Sweep <= 60, "Add3", 
#                     ifelse(rowData(se_ROMK_assigned)$Sweep >60 & rowData(se_ROMK_assigned)$Sweep <= 84,"Add4", NA))))

#sweeps_to_use <- which(rowData(se_ROMK_assigned)$Additions == "Add1")

#se_ROMK_assigned <- colAG(se_ROMK_assigned, assayList = c("Erev"), sweeps = sweeps_to_use)

#se_ROMK_assigned <- se_ROMK_assigned[, complete.cases(se_ROMK_assigned$Erev_mean)]

#se_ROMK_assigned <- se_ROMK_assigned[, colData(se_ROMK_assigned)$Erev_mean < -0.03 ]

#se_ROMK_assigned$Erev_mean <- se_ROMK_assigned$Erev_mean*1000

plot_well_assignment(se_ROMK_assigned)

rowData(se_ROMK_assigned)

well <- "I10"
imageval(se_ROMK_assigned, well, "22W14457", green_slice = 3, red_slice = 2) 

colData(se_ROMK_assigned[,se_ROMK_assigned$Well == well])
assays(se_ROMK_assigned[,se_ROMK_assigned$Well == well])$Erev*1000

colData(se_ROMK_assigned)[colData(se_ROMK_assigned)$Well == "K04", "C3"]

groups <- c(
  rep("mScarlett", 4),
  rep("GFP", 4),
  rep("Mix", 12),
  rep("Empty", 4)
)

se_ROMK_assigned <- group_assignment(se_ROMK_assigned, se = "Yes", pattern = "Cycle", cycle_pattern = groups)

```

Clustering solely based on ROMK channel (C3)
```{r}
se_ROMK_assigned_ROMKonly <- assign_cell_FINAL(
  SE = se_romk,
  channels = c("C3"),
  value_col = "Mean",
  classification_method = "clustering",
  color_output = "Color_cluster",
  plot_umap = FALSE,
  k_centers = 3
)
df <- as.data.frame(colData(se_ROMK_assigned_ROMKonly))
ggplot(df, aes(x = cluster, y = feature_C3_scaled, color = cluster)) +
  geom_jitter(width = 0.2, alpha = 0.7, size = 2) +
  theme_minimal() +
  labs(title = "Clustering on C3 only", y = "log1p (C3 Mean)", x = "Cluster")

saveRDS(se_ROMK_assigned_ROMKonly, "/Users/athenaschumacher/Downloads/E-Phac:Robinson_Labs/SE_ROMKchanonly.rds")

```




```{r}

manual_df <- as.data.frame(colData(se_ROMK_assigned))

p1 <- ggplot(manual_df, aes(x = UMAP1, y = UMAP2, color = Color_manual)) +
  geom_point(alpha = 0.7, size = 2) +
  scale_color_manual(values = c("red" = "red", "green" = "green", "black" = "black")) +
  theme_minimal() +
  labs(
    title = "UMAP of Scaled Features",
    subtitle = "Manual Cell Assignment",
    x = "UMAP1", y = "UMAP2"
  )

p2 <- ggplot(manual_df, aes(x = UMAP1, y = UMAP2, color = Color_cluster)) +
  geom_point(alpha = 0.7, size = 2) +
  scale_color_brewer(palette = "Set1", name = "Cluster") +
  theme_minimal() +
  labs(
    title = "UMAP of Scaled Features",
    subtitle = "Clusters assigned via k-means on UMAP",
    x = "UMAP1", y = "UMAP2"
  )

grid.arrange(p1, p2, ncol=2)

```



Go through the individual channels
```{r}

col_df <- as.data.frame(colData(se_ROMK_assigned))

thresh_list <- c(C1 = 0.67, C2 = 0.65, C3 = 0.48)

for (channel in names(thresh_list)) {
  feat_col <- paste0("feature_", channel, "_scaled")
  bin_col <- paste0(channel, "_binary")
  
  if (!feat_col %in% colnames(col_df)) {
    warning(paste("Column", feat_col, "not found in colData. Skipping."))
    next
  }
  col_df[[bin_col]] <- ifelse(col_df[[feat_col]] > thresh_list[[channel]], 1, 0)
}

for (col in setdiff(colnames(col_df), colnames(colData(se_ROMK_assigned)))) {
  colData(se_ROMK_assigned)[[col]] <- col_df[[col]]
}

colData(se_ROMK_assigned)$Overall_Positive <- with(col_df, ifelse(C1_binary == 1 & C2_binary == 1 & C3_binary == 1, 1, 0))

col_df$Color_binary <- with(col_df, case_when(
  C1_binary == 1 & C2_binary == 1 & C3_binary == 1 ~ "white", #not-induced
  C1_binary == 1 & C2_binary == 1 & C3_binary == 0 ~ "yellow", #ambiguous
  C1_binary == 1 & C2_binary == 0 & C3_binary == 1 ~ "turquoise", #induced
  C1_binary == 0 & C2_binary == 1 & C3_binary == 1 ~ "orange", #ambiguous
  C1_binary == 1 & C2_binary == 0 & C3_binary == 0 ~ "green", #induced
  C1_binary == 0 & C2_binary == 1 & C3_binary == 0 ~ "red", #not induced
  C1_binary == 0 & C2_binary == 0 & C3_binary == 1 ~ "navy", #induced
  TRUE ~ "black" 
))

colData(se_ROMK_assigned)$Color_binary <- col_df$Color_binary

col_df$Induction_status <- with(col_df, case_when(
  Color_binary %in% c("turquoise", "green", "navy") ~ "induced",
  Color_binary %in% c("white", "red") ~ "not_induced",
  Color_binary == c("yellow", "orange") ~ "ambiguous",
  TRUE ~ "unknown"
))

col_df$Induction_status <- factor(col_df$Induction_status,
                                   levels = c("induced", "not_induced", "ambiguous", "unknown"))

colData(se_ROMK_assigned)$Induction_status <- col_df$Induction_status

plot_well_binary_assignment(se_ROMK_assigned, values = c(
        "red" = "red",
        "green" = "green",
        "navy" = "navy",
        "yellow" = "yellow",
        "orange" = "orange",
        "turquoise" = "turquoise",
        "white" = "white",
        "black" = "grey"
      ))

plot_well_binary_assignment(se_ROMK_assigned, color_col = "Induction_status", values = c(
        "induced" = "steelblue",
        "not_induced" = "tomato",
        "ambiguous" = "gold",
        "unknown" = "grey"
      ) , title = "Induction Status Map")

colData(se_ROMK_assigned)[40:45, 158:162]
```



Compare ROMK between empty and induced cells

21:24
```{r}

col_df <- as.data.frame(colData(se_ROMK_assigned))

col_df$Column <- as.numeric(col_df$Column)

subset_df <- col_df[col_df$Column %in% 21:24, ]

mean_C3_last_cols <- mean(subset_df$feature_C3_scaled, na.rm = TRUE)
mean_C3_last_cols

median_C3_last_cols <- median(subset_df$feature_C3_scaled, na.rm = TRUE)
median_C3_last_cols

```

5:8
```{r}

col_df$Column <- as.numeric(col_df$Column)

subset_5_8 <- col_df[col_df$Column %in% 5:8, ]

mean_C3_cols_5_8 <- mean(subset_5_8$feature_C3_scaled, na.rm = TRUE)
mean_C3_cols_5_8

median_C3_cols_5_8 <- median(subset_5_8$feature_C3_scaled, na.rm = TRUE)
median_C3_cols_5_8

```


```{r}
col_df$Column_Group <- case_when(
  col_df$Column %in% 5:8  ~ "Cols_5_8",
  col_df$Column %in% 21:24 ~ "Cols_21_24",
  TRUE ~ NA_character_
)

# Filter only those two groups
plot_df <- subset(col_df, !is.na(Column_Group))

# Boxplot
ggplot(plot_df, aes(x = Column_Group, y = feature_C3_scaled, fill = Column_Group)) +
  geom_boxplot() +
  theme_minimal() +
  labs(title = "Comparison of feature_C3_scaled", y = "C3 Scaled", x = "Column Group")


#################

col_df <- as.data.frame(colData(se_ROMK_assigned))
col_df$Column <- as.numeric(col_df$Column)

# Add grouping variable
col_df <- col_df %>%
  mutate(Column_Group = case_when(
    Column %in% 5:8 ~ "Cols_5_8",
    Column %in% 21:24 ~ "Cols_21_24",
    TRUE ~ NA_character_
  )) %>%
  filter(!is.na(Column_Group))  # Keep only wells from those column groups

# Pivot to long format for the 3 channels
long_df <- col_df %>%
  pivot_longer(
    cols = c(feature_C1_scaled, feature_C2_scaled, feature_C3_scaled),
    names_to = "Channel",
    values_to = "Scaled_Intensity"
  ) %>%
  mutate(Channel = gsub("feature_|_scaled", "", Channel))  


ggplot(long_df, aes(x = Column_Group, y = Scaled_Intensity, fill = Column_Group)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.8) +
  geom_jitter(width = 0.1, alpha = 0.4, size = 1) +
  facet_grid(. ~ Channel) +
  theme_minimal() +
  labs(
    title = "Comparison of Scaled Intensities Across Channels",
    x = "Column Group",
    y = "Scaled Intensity (0–1)"
  ) +
  theme(legend.position = "none")

```


