---
title: "Explore_Dimensionality_Reduction"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Explore_Dimensionality_Reduction}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Load Package and Data

```{r setup}
devtools::load_all()

data("se_iN")
data("se_hAG")

pathDF <- "C:/Users/davec/Documents/R-Markdowns/General/Blockcourse/IV neurons_12.47.37_RAW.xlsx"
se <- prepareSE(pathDF = pathDF)
colData(se)$Plate_ID <- "18T05487"
pathImg <- "C:/Users/davec/Documents/R-Markdowns/General/Blockcourse/Output_291124_BME308_DIV_18T05487.db"

img <- prepareImgDF(pathImg, scale_num = TRUE)
img.coloc <- prepareImgDF(pathImg, analysis = "coloc", scale_num = TRUE)

se <- mergeSEandImg(se, img)
se <- mergeSEandImg(se, img.coloc, tableType = "coloc")

colData(se)
assays(se)
se <- colAG(se,  c("Seal", "Series", "Capacitance"))
colData(se)

se$DIV <- ifelse(as.numeric(se$Column) %% 2 == 0, "DIV7", "DIV14")
colData(se)$C2

assays(se)$CurDens.min <- 10^12*assay(se, "Minima") / assay(se, "Capacitance")
assays(se)$CurDens.max <- 10^12*assay(se, "Maxima") / assay(se, "Capacitance")

```



```{r}


```




### Dimensionality Reduction Based on QCs

```{r}

se <- colAG(se,  c("Seal", "Series", "Capacitance"))

se <- reducedDim.Cellwise(se, assayList = c("Seal", "Series", "Capacitance"), scaling = "global", byRow=FALSE)

plotDimRed(se, "UMAP",  colorColumns = c("Seal_mean", "Series_mean", "Capacitance_mean"))
plotDimRed(se, "TSNE",  colorColumns = c("Seal_mean", "Series_mean", "Capacitance_mean"))

colData(se)
plotAssayVSSweeps(se,  c("Seal", "Series", "Capacitance"), rowCol = "V_Clamp", colorGroup = "QC", wrapFormula = cluster.umap~variable)

plotAssayVSSweeps(se,  c("Minima", "Maxima", "Capacitance"), rowCol = "V_Clamp", colorGroup = "cluster.umap", wrapFormula = QC~variable)

```

## Dimensionality Reduction Based on Minima and Maxima

```{r}
se <- se[, se$QC == TRUE]

colData(se)
se
se <- reducedDim.Cellwise(se, assayList = c("CurDens.min", "CurDens.max"), scaling = "within", byRow = TRUE)

plotDimRed(se, "UMAP",  colorColumns = c("DIV"))
plotDimRed(se, "UMAP",  colorColumns = c("C2.Mean", "C3.Mean"))

plotDimRed(se, "TSNE",  colorColumns = c("DIV"))

plotAssayVSSweeps(se,  c("Seal", "Series", "Capacitance"), rowCol = "V_Clamp", colorGroup = "cluster.umap", wrapFormula = .~variable)

plotAssayVSSweeps(se,  c("Minima", "Maxima", "Capacitance"), rowCol = "V_Clamp", colorGroup = "DIV", wrapFormula = cluster.umap~variable)


plotAssayVSSweeps(se,  c("CurDens.min", "CurDens.max", "Capacitance"), rowCol = "V_Clamp", colorGroup = "DIV", wrapFormula = cluster.umap~variable) + ylab("Current Density (pA/pF)")



```

## Dimensionality Reduction Based on Imaging Data

```{r}

devtools::load_all()
se <- se[,se$QC == TRUE]
se <- reducedDim.Cellwise(se, colNames  = c("C2.Mean_Scaled", "C3.Mean_Scaled", "C2.Area_Scaled", "C3.Area_Scaled"), scaling = "within", byRow=FALSE)
plotDimRed(se, "PCA",  colorColumns = "DIV")
plotDimRed(se, "UMAP",  colorColumns = "DIV")
plotDimRed(se, "TSNE",  colorColumns = "DIV")


plotDimRed(se, "UMAP",  colorColumns = c("C2.Mean_Scaled", "C3.Mean_Scaled"))
plotDimRed(se, "TSNE",  colorColumns =  c("C2.Mean_Scaled", "C3.Mean_Scaled"))

plotAssayVSSweeps(se,  c("Seal", "Series", "Capacitance"), rowCol = "V_Clamp", colorGroup = "cluster.umap", wrapFormula = .~variable)

plotAssayVSSweeps(se,  c("Minima", "Maxima", "Capacitance"), rowCol = "V_Clamp", colorGroup = "cluster.umap", wrapFormula = DIV~variable)

```


## Dimensionality Reduction based on all parameters


```{r}
devtools::load_all()

assayList <- c("Maxima", "Minima","CurDens.min", "CurDens.max", "Seal", "Series", "Capacitance")
colList <-  c("C2.Mean_Scaled", "C3.Mean_Scaled", "C2.Area_Scaled", "C3.Area_Scaled")

se <- reducedDim.Cellwise(se, assayList = assayList,colNames = colList, scaling = "global", byRow=TRUE, k_clusters = 3)

plotDimRed(se, "PCA",  colorColumns = "DIV")
plotDimRed(se, "UMAP",  colorColumns = "DIV")
plotDimRed(se, "TSNE",  colorColumns = "DIV")

plotDimRed(se, "UMAP",  colorColumns = c("C2.Mean_Scaled", "C3.Mean_Scaled"))

plotDimRed(se, "TSNE",  colorColumns = c("Seal_mean", "Series_mean", "Capacitance_mean"))
plotDimRed(se, "TSNE",  colorColumns = c("C2.Mean", "C3.Mean"))


plotAssayVSSweeps(se,  c("Minima", "Maxima"), rowCol = "V_Clamp", colorGroup = "cluster.umap", wrapFormula = DIV~variable)

assays(se)
plotAssayVSSweeps(se,  c("CurDens.min", "CurDens.max"), rowCol = "V_Clamp", colorGroup = "DIV", wrapFormula = cluster.umap~variable)

plotAssayVSSweeps(se,  c("CurDens.min", "CurDens.max"), rowCol = "V_Clamp", colorGroup = "DIV", wrapFormula = cluster.tsne~variable)




```

MUVON

```{r}


wd_path <- "C:\\Users\\davec\\Documents\\R-Markdowns\\General\\MUVON\\Report_MUVON_17042025/"

l_files <- list.files(path = wd_path ,pattern = "*_leakCorr", recursive = TRUE, full.names = TRUE)
#l_files <- l_files[!grepl("SET", l_files) & !grepl("Jupyter", l_files) & !grepl("~", l_files)]

l_files <- l_files[!grepl("~", l_files)]
length(l_files)

l_files <- l_files[!(grepl("Run1_First", l_files)&!grepl("v2", l_files))]
l_files <- l_files[grepl("v2", l_files)]

se <- prepareSE(l_files)

letter2number <- function(x) {utf8ToInt(x) - utf8ToInt("A") + 1L}
se$RowNum <- sapply(se$Row, function(c){letter2number(c)})
se$ColNum <- as.numeric(se$Column)
se$Condition <- ifelse(se$RowNum %in% 1:4, "Mouse MPC",
                                  ifelse(se$RowNum %in% 5:8, "MPC#1",
                                         ifelse(se$RowNum %in% 9:12, "MPC#2",
                                                ifelse(se$RowNum %in% 13:16, "MPC#3", NA))))

se <- se[,se$QC == TRUE]


se <- reducedDim.Cellwise(se, assayList = c("Maxima", "Minima"))




se[,is.na(se$Condition)]$Well


plotDimRed(se, "UMAP", colorColumns = "Condition")


plotAssayVSSweeps(se, c("Maxima", "Minima", "Capacitance"), rowCol="V_Clamp", colorGroup = "Condition", wrapFormula =variable ~ cluster.umap)


```


## Old primary neuron data


```{r}

l_files <- c("C:\\Users\\davec\\Documents\\R-Markdowns\\General\\PrimaryNeurons\\241119\\L-Type-IV neurons_15.03.57.xlsx", "C:\\Users\\davec\\Documents\\R-Markdowns\\General\\PrimaryNeurons\\241119\\IV neurons_15.03.57.xlsx")



se_l <- prepareSE(l_files[1])

l.path <- "C:\\Users\\davec\\Documents\\R-Markdowns\\General\\Blockcourse\\Outputtables\\Output_PNC_PTX-Mock_LType.db"

df_img.l <- prepareImgDF(l.path, id_cols = c("Well",
                                              "Image_ID","Channel_Name",
                                              "Selection","Selection_Area"))

se_l <- prepareSE(l_files[1])
se_s <- prepareSE(l_files[2])

df_img.l$Plate_ID <- "L-Type"
se_l$Plate_ID <- "L-Type"

df_img.l$Image_Type <- "fluor"

unique(df_img.l$Well)

se_l <- mergeSEandImg(se_l, df_img.l, tableType = "pa")


se_s$Plate_ID <- "S-Type"

s.path <- "C:\\Users\\davec\\Documents\\R-Markdowns\\General\\Blockcourse\\Outputtables\\Output_PNC_PTX-Mock_SType.db"

df_img.s <- prepareImgDF(s.path, id_cols = c("Well",
                                              "Image_ID","Channel_Name",
                                              "Selection","Selection_Area"))

df_img.s$Plate_ID <- "S-Type"
se_s$Plate_ID <- "S-Type"

df_img.s$Image_Type <- "fluor"

se_s <- mergeSEandImg(se_s, df_img.s, tableType = "pa")


se <- SEtools::mergeSEs(list(L = se_l, S= se_s), do.scale = FALSE)

se <- SingleCellExperiment::SingleCellExperiment(
  assays= assays(se),
  rowData = rowData(se),
  colData = colData(se))

letter2number <- function(x) {utf8ToInt(x) - utf8ToInt("A") + 1L}
se$RowNum <- sapply(se$Row, function(c){letter2number(c)})
se$ColNum <- as.numeric(se$Column)
se$PTXTreatment <- ifelse(se$ColNum %% 2 == 0, "Mock", "PTX")

assays(se)$CurDens.min <- 10^12*assay(se, "Minima") / assay(se, "Capacitance")
assays(se)$CurDens.max <- 10^12*assay(se, "Maxima") / assay(se, "Capacitance")

se <- se[,se$QC == TRUE]

colData(se)$C3.Mean

plotAssayVSSweeps(se, c("CurDens.min", "CurDens.max"), rowCol = "V_Clamp", colorGroup = "PTXTreatment", wrapFormula = variable~Plate_ID)


se <- reducedDim.Cellwise(se, colNames  = c("C2.Mean", "C3.Mean"), k_clusters = 3)

se <- reducedDim.Cellwise(se, assayList = c("Seal", "Series", "Capacitance"), k_clusters = 3)

plotDimRed(se, redDim.method = "UMAP", colorColumns = c("PTXTreatment","C2.Mean", "C3.Mean"))

plotAssayVSSweeps(se, assayList = c("Seal", "Series", "Capacitance"), rowCol = "V_Clamp",  colorGroup = "PTXTreatment", wrapFormula = variable~cluster.umap)

plotAssayVSSweeps(se[,se$QC == TRUE], assayList = c("Maxima", "Minima", "CurDens.min", "CurDens.max", "Capacitance", "Series", "Seal"), rowCol = "V_Clamp",  colorGroup = "PTXTreatment", wrapFormula = variable~.)


```



## ROMK

```{r}
devtools::load_all()


data(se_romk)
romk <- se_romk

rowData(romk)$Addition <- ifelse(is.na(rowData(romk)$Compound), 1,
                                 ifelse(grepl("Ref", rowData(romk)$Compound), 2,
                                        ifelse(grepl("K", rowData(romk)$Compound) & as.numeric(rowData(romk)$Sweep) < 65,3, 4)))

rowData(romk)$Addition

colData(romk)$ColNum <- as.numeric(colData(romk)$Column)
colData(romk)$Celltype <- ifelse(romk$ColNum <= 4, "mScarlett",
                                 ifelse(romk$ColNum > 4 & romk$ColNum <= 8, "GFP",
                                 ifelse(romk$ColNum > 8 & romk$ColNum <= 20, "mixed",
                                 "empty")))
colData(romk)

moltenSE <- sechm::meltSE(romk, features = row.names(rowData(romk)), assayName = "Erev", rowDat.columns = "Addition") 


ggplot(moltenSE, aes(x=Addition, y=Erev, color=Celltype)) + 
  ggplot2::stat_summary(geom='errorbar',fun.data=mean_se, size=1, alpha=0.6) +
    ggplot2::stat_summary(geom='line', fun = "mean", size=1, alpha=1) +
    ggplot2::theme_minimal(base_size = 16)


ggplot(moltenSE, aes(x=Addition, y=Erev, color=Celltype, fill=Celltype)) + ggplot2::stat_summary(geom='errorbar',fun.data=mean_se, size=1, alpha=0.6) +
    ggplot2::stat_summary(geom='line', fun = "mean", size=1, alpha=1) +
    ggplot2::theme_minimal(base_size = 16) + facet_grid(~Celltype)

ggplot(moltenSE, aes(x=Addition, y=Erev, color=Well, group=Well)) +
  geom_line() + facet_grid(~Celltype) + guides(color="none")


romk <- colAG(romk, assayList = c("Erev", "X.100mV", "X.20mV", "Seal"), sweeps = row.names(subset(rowData(romk), Addition==1)))
romk <- reducedDim.Cellwise(romk, assayList= c("Erev", "X.100mV", "X.20mV", "Cap", "Seal"))
plotDimRed(romk, redDim.method = "PCA", colorColumns = c("Erev_mean", "Celltype", "QC"))


colData(romk)$Erev_mean <- colData(romk)$Erev_mean*1000
#romk <- romk[,romk$Erev_mean < -15]

library(SingleCellExperiment)
assays(romk)

colData(romk)



romk <- SEtools::aggSE(romk, by = "Addition")

romk <- reducedDim.Cellwise(romk, assayList= c("Erev", "X.100mV", "X.20mV", "Cap", "Seal"))


plotDimRed(romk, redDim.method = "PCA", colorColumns = c("Erev_mean", "Celltype", "QC"))
colData(romk)$Erev_mean <- colData(romk)$Erev_mean*1000

plotDimRed(romk, redDim.method = "UMAP", colorColumns = c("Erev_mean", "Celltype", "Seal_mean"))

moltenSE <- sechm::meltSE(romk, features = row.names(rowData(romk)), assayName = c("Erev", "X.100mV", "X.20mV", "Seal"), rowDat.columns = c("Addition", "Sweep")) 

meltdf <- reshape2::melt(moltenSE, measure.vars = c("Erev", "X.100mV", "X.20mV", "Seal"))

ggplot(meltdf, aes(x=Addition, y=value, color=Celltype, fill=Celltype)) + ggplot2::stat_summary(geom='errorbar',fun.data=mean_se, size=1, alpha=0.6) +
    ggplot2::stat_summary(geom='line', fun = "mean", size=1, alpha=1) +
    ggplot2::theme_minimal(base_size = 16) + facet_wrap(variable~cluster.umap, scales="free", ncol=3)

meltdf <- subset(moltenSE, cluster.umap != 1)



library(lmerTest)
library(emmeans)

mod <- lmer(Erev ~ Celltype*cluster.umap  + (1|Well), subset(meltdf, Addition == 1))
summary(mod)
emmeans(mod, trt.vs.ctrl ~ Celltype, ref="GFP")
emmeans(mod, pairwise ~ Celltype | cluster.umap)
emmeans(mod, pairwise ~ cluster.umap | Celltype)
emmeans(mod, pairwise ~ cluster.umap * Celltype)

ggplot(moltenSE, aes(x=Celltype, y=X.100mV_mean, color=Celltype, fill=Celltype)) + geom_point() +  geom_boxplot(alpha=0.4)+ facet_grid(.~cluster.umap)

subse <- romk[,romk$cluster.umap == 2]


subse <- reducedDim.Cellwise(subse, assayList= c("Erev", "X.100mV", "X.20mV"))
plotDimRed(subse, redDim.method = "UMAP", colorColumns = c("Erev_mean", "Celltype"))

ggplot(subset(moltenSE, Addition==1), aes(x=Erev_mean, color=Celltype)) + geom_histogram(alpha=0, bins = 100) + facet_grid(cluster.umap~.)

subset(rowData(romk), Addition==1)

rowData(romk)

ggplot(subset(moltenSE, Addition==2 & Sweep == 55), aes(x=Erev*1000, y = (10^12)*X.100mV, color=Celltype)) + geom_point() + facet_grid(cluster.umap~.)

ggplot(subset(moltenSE, Addition==2 & Sweep == 55), aes(x=Erev*1000, y = (10^9)*X.20mV, color=Celltype)) + geom_point() + facet_grid(cluster.umap~.)

ggplot(subset(moltenSE, Addition==1 & Sweep == 40), aes(x=Erev*1000, y = (10^9)*X.20mV, color=Celltype)) + geom_point() + facet_grid(cluster.umap~.)

ggplot(subset(moltenSE), aes(x=Erev*1000, y = (10^9)*X.20mV, color=Celltype)) + geom_point() + facet_grid(cluster.umap~Addition)
ggplot(subset(moltenSE), aes(x=Erev*1000, y = (10^9)*X.100mV, color=Celltype)) + geom_point() + facet_grid(cluster.umap~Addition)


```



## Primary Neurons

```{r}

devtools::load_all()

data("se_pn")

se_pn

se_pn$ColNum <- as.numeric(se_pn$Column)

se_pn$PTXTreatment <- ifelse(se_pn$ColNum %% 2 == 0, "Mock", "PTX")

assays(se_pn)$CurDens.min <- 10^12*assay(se_pn, "Minima") / assay(se_pn, "Capacitance")
assays(se_pn)$CurDens.max <- 10^12*assay(se_pn, "Maxima") / assay(se_pn, "Capacitance")

se_pn <- se_pn[,se_pn$QC == TRUE]

colData(se_pn)$C3.Mean

plotAssayVSSweeps(se_pn, c("CurDens.min", "CurDens.max"), rowCol = "V_Clamp", colorGroup = "PTXTreatment", wrapFormula = variable~.)

se_pn <- reducedDim.Cellwise(se_pn,assayList = c("Capacitance", "Seal", "Series"), colNames  = c("C2.Mean", "C3.Mean", "C2.Area", "C3.Area"), k_clusters = 5)

#se_pn <- reducedDim.Cellwise(se_pn, assayList = c("Seal", "Series", "Capacitance"), k_clusters = 3)

plotDimRed(se_pn, redDim.method = "TSNE", colorColumns = c("PTXTreatment","C2.Mean", "C3.Mean", "QC"))

plotAssayVSSweeps(se_pn, c("Minima", "Maxima", "Capacitance"), rowCol = "V_Clamp", colorGroup = "PTXTreatment", wrapFormula = variable~cluster.umap)

```

