---
title: "Imaging_script_Gen"
author: "Athena Schumacher"
date: "2025-05-21"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Load Useful Packages and Functions

```{r message=FALSE, warning=FALSE}

source("/Users/athenaschumacher/Downloads/E-Phac:Robinson_Labs/ephacRTools/R/imagingTools.R")
source("/Users/athenaschumacher/Downloads/E-Phac:Robinson_Labs/ephacRTools/R/utilityTools.R")
source("/Users/athenaschumacher/Downloads/E-Phac:Robinson_Labs/ephacRTools/R/prepareSE.R")
source("/Users/athenaschumacher/Downloads/E-Phac:Robinson_Labs/ephacRTools/R/colDatTools.R")

```


```{r}

devtools::load_all()

data("se_iN")

<<<<<<< HEAD
=======
data("se_romk")

>>>>>>> fceaa49 (Updated scripts)
colData(se_iN)[15:25,]

```

```{r}

wells <- se_iN$Well
plateIDs <- se_iN$Plate_ID

parent_folder <- "/Volumes/staff/ephacoffice/DColameo/DATA/iPSC_Tricultures"

image_paths_list <- mapply(function(well, plate, location) {
  image_paths(parent_folder, idx = well, plate = plate, location = 7)
}, well = wells, plate = plateIDs, SIMPLIFY = FALSE)

colData(se_iN)$Image_paths <- image_paths_list 

# Check 
colData(se_iN)$Image_paths

se_iN[,se_iN$Well == "H05"]$Image_paths

```

Visualize the different channels for a given well of a given plate
```{r}

imageval(se_iN, "C09", "18T39265")

```



Adrenal cells

```{r}

wd_path <- "/Users/athenaschumacher/Downloads/E-Phac:Robinson_Labs/excel_files"

<<<<<<< HEAD
pathToTable <- "/Users/athenaschumacher/Downloads/E-Phac:Robinson_Labs/excel_files/NCI_ramp_ATP1A1_280225_18T39417.xlsx"
=======
pathToTable <- "/Users/athenaschumacher/Downloads/E-Phac:Robinson_Labs/excel_files/NCI_ramp_ATP1A1_080325_18T39421.xlsx"

plate_ID <- "18T39421"
>>>>>>> fceaa49 (Updated scripts)

df <- prep_excel(pathToTable)

df <- prep_df(wd_path, df)

<<<<<<< HEAD
df <- filtered_df(df, "18T39417")

df <- group_assignment(df, pattern = "Cycle", cycle_pattern = c("HP", "WT", "HP"))
=======
df <- filtered_df(df, plate_ID, ion = "Na")

#df <- group_assignment(df, se = "No", pattern = "Cycle", cycle_pattern = c("HP", "WT","Donor2"))
df <- group_assignment(df, se = "No", pattern = "Cycle", cycle_pattern = c("Donor1", "Donor2"))

>>>>>>> fceaa49 (Updated scripts)

```

```{r}
se_hAG <- prepareSE(pathToTable)

parent_folder <- "/Volumes/staff/ephacoffice/DColameo/DATA/human_AG_Sinergia"
<<<<<<< HEAD
plate = "18T39417"
=======
plate = plate_ID
>>>>>>> fceaa49 (Updated scripts)

wells <- se_hAG$Well
plateIDs <- se_hAG$Plate_ID

<<<<<<< HEAD
image_paths_list <- mapply(function(well, plate, location=6) {
  image_paths(parent_folder, idx = well, plate = plate, location = 6)
=======
image_paths_list <- mapply(function(well, plate, location=7) {
  image_paths(parent_folder, idx = well, plate = plate, location = 7)
>>>>>>> fceaa49 (Updated scripts)
}, well = wells, plate = plateIDs, SIMPLIFY = FALSE)

colData(se_hAG)$Image_paths <- image_paths_list 

# Check 
colData(se_hAG)$Image_paths

se_hAG[,se_hAG$Well == "H05"]$Image_paths

```


```{r}
se_coldata <- as.data.frame(colData(se_hAG))

df_clean <- df %>%
  select(Well, Plate_ID, Compound, Group) %>%
  distinct(Well, Plate_ID, .keep_all = TRUE)

matched <- left_join(se_coldata, df_clean, by = c("Well", "Plate_ID"))

se_hAG$Compound <- matched$Compound
se_hAG$Group <- matched$Group

colData(se_hAG)[30:40,]
```


<<<<<<< HEAD
Save additions in colData
=======
Save additions in colData (optional) -> skip to next part
>>>>>>> fceaa49 (Updated scripts)
```{r}
df_mean_byConc <- rowAG(se_hAG, assay_name = "Erev", FUN=mean, mode="by.period")

rd <- as.data.frame(rowData(se_hAG))
rd$Na_Conc = case_when(
        rd$Sweep <= 24 ~ 0.08,
        rd$Sweep <= 42 ~ 0.04,
        rd$Sweep <= 60 ~ 0.02,
        rd$Sweep <= 84 ~ 0.01,
        TRUE ~ NA_real_
)
rd$Step <- factor(
  cut(rd$Sweep, breaks = c(0, 24, 42, 60, 84, Inf), 
      labels = c("Add1", "Add2", "Add3", "Add4", "Out")),
  levels = c("Add1", "Add2", "Add3", "Add4", "Out")
  )
rowData(se_hAG) <- DataFrame(rd)

df_mean  <- rowAG(se_hAG, assay_name = "Erev", FUN = mean)

cd <- as.data.frame(colData(se_hAG))
cd <- left_join(cd, df_mean, by = c("Well","Plate_ID","QC","Compound","Group"))
colData(se_hAG) <- DataFrame(cd)

se_hAG <- df_mean_byConcse_hse_hAGAG 

```

Save Additions as assays
```{r}

se1 <- row_aggregate_SE(se_hAG,
                        metrics = c("Erev"),
                        FUN     = mean,
                        mode    = "by.period")

# 2) mean of last 5 sweeps
se2_mean <- row_aggregate_SE(se_hAG,
                        metrics = "Erev",
                        FUN     = mean,
                        mode    = "last.n",
                        last.n  = 5)

# 2) median of last 5 sweeps 
se2_med <- row_aggregate_SE(se_hAG,
                        metrics = "Erev",
                        FUN     = median,
                        mode    = "last.n",
                        last.n  = 5)

## Check
se_period <- se1

assayNames(se_period)

mat <- assay(se_period, "Erev")
dim(mat)
rownames(mat)
colnames(mat)[1:10]

mat[, 1:6]
head(mat)

summary(as.numeric(mat))

```

<<<<<<< HEAD
```{r}
SETools::aggSE()
```


=======

Imaging Data
```{r}

directory <- "/Users/athenaschumacher/Downloads/E-Phac:Robinson_Labs/imaging_data"
extension <- "\\.db$"  # Regular expression for files ending with .db

file_list <- list.files(path = directory, pattern = extension, full.names = TRUE)
file_list <- "/Users/athenaschumacher/Downloads/E-Phac:Robinson_Labs/imaging_data/Output_n1_08.03.db"

df_img <- prepareImgDF(file_list, scale_num = TRUE, analysis = "coloc")
se_hAG_test <- mergeSEandImg(se_hAG, df_img, tableType = "coloc")
df_img <- prepareImgDF(file_list, scale_num = TRUE, analysis = "pa")
se_hAG_test <- mergeSEandImg(se_hAG_test, df_img, tableType = "pa")

#data(se_hAG)
#colData(se_hAG)$C2[complete.cases(colData(se_hAG)$C2),]


se_hAG_test2 <- assign_cell_from_SE_v2(
  SE = se_hAG_test,
  return_joined_SE = TRUE,
)

#well_df <- map_dfr(file_list, assigncell, analysis_type ="pa")

#well_df <- well_df %>%
#  filter(Plate_ID == "18T39417")

#cols_to_add <- c("Mean_Red_scaled", "Mean_Green_scaled", "Color")

#se_test <- add_imagingcols_toSE(SE = se_hAG, imaging_df = well_df, columns_to_add = cols_to_add)

set.seed(42)

se_test <- reducedDim.Cellwise(se_test, colNames= c("Mean_Green_scaled", "Mean_Red_scaled"))


plotDimRed(se_test, redDim.method = "UMAP", colorColumns = c("Mean_Green_scaled", "Mean_Red_scaled","Color",  "Group"))



se_red <- se_test[, !is.na(se_test$Color)]

se_red <- reducedDim.Cellwise(se_red, colNames= c("Mean_Green_scaled", "Mean_Red_scaled"))

se_red <- colAG(se_red, assayList = c("Erev"), sweeps = row.names(rowData(se_red)), suffx=".add1")
colData(se_red)

plotDimRed(se_red, redDim.method = "UMAP", colorColumns = c("Mean_Green_scaled", "Mean_Red_scaled","Color",  "Group"))

colData(se1)

se_hAG_test2$Mean.Scaled <- se_hAG_test2$C2$Mean_Scaled

```


GENERALIZED VERSION
```{r}
se_hAG_GEN <- assign_cell_from_SE_GENv2(
  SE = se_hAG_test,
  channels = c("C2", "C3"),
  value_col = "Mean",
  color_logic = function(df) {
    red <- df$feature_C3_scaled
    green <- df$feature_C2_scaled
    case_when(
      red < 0.05 & green < 0.05 ~ "black",
      red >= 0.2 & green >= 0.1 ~ "yellow",
      green >= 0.1 ~ "green",
      red >= 0.2 ~ "red",
      TRUE ~ "black"
    )
  }
)


se_hAG_GEN2 <- assign_cell_from_SE_GENv2(
  SE = se_hAG_test,
  channels = c("C2", "C3"),
  value_col = "IntDen",
  color_logic = NULL
)


se_GENtest <- assign_cell_FINAL(
  SE = se_hAG_test,
  channels = c("C2", "C3"),
  value_col = "Mean",
  classification_method = "clustering",
  color_output = "Color_cluster",
  plot_umap = TRUE,
  k_centers = 4
)


se_GENtest <- assign_cell_FINAL(
  SE = se_GENtest,
  channels = c("C2", "C3"),
  value_col = "Mean",
  classification_method = "manual",
  color_output = "Color_manual"
)

se_GENtest <- colAG(se_GENtest, sweeps = c(1:10), assayList = c("Erev"))

se2 <- se_GENtest[, complete.cases(se_GENtest$Erev_mean)]

se2 <- se2[, colData(se2)$Erev_mean < -0.03 ]

se2$Erev_mean <- se2$Erev_mean*1000


se2_df <- as.data.frame(colData(se2))
se2_df$Column <- as.numeric(se2_df$Column)
p <- ggplot(se2_df, aes(x = Column, y = Row, fill = Color_manual)) +
    geom_tile(color = "black", linewidth = 0.5) +
    scale_fill_manual(values = c("red" = "red", "green" = "green", "yellow" = "yellow", "black" = "grey")) +
    scale_x_continuous(breaks = 1:24) +
    scale_y_discrete(limits = rev(sort(unique(se2_df$Row)))) +
    geom_text(aes(label = Well), color = "black") +
    labs(title = paste("Well Plate Cell Assignment for", se2_df$Plate_ID),
         x = "Column", y = "Row")

  print(p)



df_plot <- as.data.frame(colData(se_GENtest))
#df_plot_man <- as.data.frame(colData(se_GENtest_MAN))

p1 <- ggplot(df_plot, aes(x = UMAP1, y = UMAP2, color = Color_manual)) +
  geom_point(size = 2, alpha = 0.7) +
  theme_minimal() +
  labs(title = "Manual Thresholding", color = "Manual") +
  scale_color_brewer(palette = "Set1")

p2 <- ggplot(df_plot, aes(x = UMAP1, y = UMAP2, color = Color_cluster)) +
  geom_point(size = 2, alpha = 0.7) +
  theme_minimal() +
  labs(title = "Clustering-Based", color = "Cluster") +
  scale_color_brewer(palette = "Set2")

# Combine plots side by side
grid.arrange(p1, p2)
```


```{r}

plot_intensity_distribution(se_hAG_test, plot_type="density")
plot_intensity_distribution(se_hAG_test, plot_type="ecdf")

TEST_SE <- assign_cell_FINAL(
  SE = se_hAG_test,
  channels = c("C2", "C3"),
  value_col = "Mean",
  classification_method = "clustering",
  color_output = "Color_cluster",
  plot_umap = TRUE,
  k_centers = 4
)


TEST_SE <- assign_cell_FINAL(
  SE = TEST_SE,
  channels = c("C2", "C3"),
  value_col = "Mean",
  classification_method = "manual",
  color_output = "Color_manual",
  threshold_mode = "manual",
  red_thresh = 0.54,
  green_thresh = 0.74
)

colData(TEST_SE)[30:40,]

TEST_SE <- colAG(TEST_SE, sweeps = c(1:10), assayList = c("Erev"))

TEST_SE2 <- se_GENtest[, complete.cases(TEST_SE$Erev_mean)]

TEST_SE2 <- TEST_SE2[, colData(TEST_SE2)$Erev_mean < -0.03 ]

TEST_SE2$Erev_mean <- TEST_SE2$Erev_mean*1000

plot_well_assignment(TEST_SE2)

```






Not final code as comparison
```{r}
se3_v1 <- assign_cell_NOTFINAL(
  SE = se_hAG_test,
  channels = c("C2", "C3"),
  value_col = "Mean",
  classification_method = "clustering",
  color_output = "Color_cluster",
  plot_umap = TRUE,
  k_centers = 4
)


se3_v1 <- assign_cell_NOTFINAL(
  SE = se3_v1,
  channels = c("C2", "C3"),
  value_col = "Mean",
  classification_method = "manual",
  color_output = "Color_manual"
)

se3 <- colAG(se3_v1, sweeps = c(1:10), assayList = c("Erev"))
se3 <- se3[, complete.cases(se_GENtest$Erev_mean)]
se3 <- se3[, colData(se3)$Erev_mean < -0.03 ]
se3$Erev_mean <- se3$Erev_mean*1000

se3_df <- as.data.frame(colData(se3))
se3_df$Column <- as.numeric(se3_df$Column)
q <- ggplot(se3_df, aes(x = Column, y = Row, fill = Color_manual)) +
    geom_tile(color = "black", linewidth = 0.5) +
    scale_fill_manual(values = c("red" = "red", "green" = "green", "yellow" = "yellow", "black" = "grey")) +
    scale_x_continuous(breaks = 1:24) +
    scale_y_discrete(limits = rev(sort(unique(se3_df$Row)))) +
    geom_text(aes(label = Well), color = "black") +
    labs(title = paste("Well Plate Cell Assignment for", se3_df$Plate_ID),
         x = "Column", y = "Row")

  print(q)
```




See the brightest ones
```{r}

df <- as.data.frame(colData(se_GENtest))

# View top 10 wells by feature_C2_scaled
top_c2 <- df %>%
  arrange(desc(feature_C2_scaled)) %>%
  select(Well, Plate_ID, feature_C2_scaled, Color_manual, Color_cluster) %>%
  slice_head(n = 10)

# View top 10 wells by feature_C3_scaled
top_c3 <- df %>%
  arrange(desc(feature_C3_scaled)) %>%
  select(Well, Plate_ID, feature_C3_scaled, Color_manual, Color_cluster) %>%
  slice_head(n = 10)

imageval(se_GENtest, "B04", "18T39417")


```



```{r}

add1 <- colAG(se1, assayList = c("Erev"), sweeps = row.names(subset(rowData(se_hAG), Addition==1)))

romk <- reducedDim.Cellwise(romk, assayList= c("Erev"))

plotDimRed(romk, redDim.method = "PCA", colorColumns = c("Erev_mean", "Celltype", "QC"))

```





SEtools::aggSE test
```{r}
library(SEtools)

periods = list(
  Add1 = 1:24,
  Add2 = 25:42,
  Add3 = 43:60,
  Add4 = 61:84
)

period_map <- bind_rows(lapply(names(periods), function(lbl) {
  data.frame(Sweep = as.integer(periods[[lbl]]), Addition = lbl, stringsAsFactors = FALSE)
}
  ))

se_hAG_Erev <- se_hAG
assays(se_hAG_Erev) <- list(Erev = assays(se_hAG)[["Erev"]])

row_df <- DataFrame(Sweep = 1:nrow(se_hAG_Erev))
row_df$Additions <- rep(c("Add1", "Add2", "Add3", "Add4"), times = c(24, 18, 18, 24))
rowData(se_hAG_Erev) <- row_df

str(rowData(se_hAG_Erev))
table(rowData(se_hAG_Erev)$Additions, useNA = "always")

ag_SE <- SEtools::aggSE(se_hAG_Erev, by = "Additions", assayFun = mean)

colData(ag_SE)[30:36,]
assay(ag_SE, "Erev")[ ,40:45]
rowData(ag_SE)$Additions


```







>>>>>>> fceaa49 (Updated scripts)
